Result<usize, std::io::Error>
